<a href="https://colab.research.google.com/github/Rizki-132/Allmateri/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

In [ ]:
import numpy as np

Array dengan rank 1 dan panjang 3.

In [ ]:
[1, 2, 3]

[1, 2, 3]

Array dengan rank 2 dan panjang 3.

In [ ]:
[[1, 2, 3], [4, 5, 6]]

[[1, 2, 3], [4, 5, 6]]

In [ ]:
a = np.array([1, 2, 3])
b = np.array([(1, 2, 3), (4, 5, 6)])

print(a)
print(b)

[1 2 3]
[[1 2 3]
 [4 5 6]]


**ndarray**: nama class untuk sebuah numpy array.

In [ ]:
# Bakal menghasilkan error karena parameter untuk np.array
# harus beruapa array
# a = np.array(1, 2, 3)

---

# Properties
* **ndarray.ndim**: dimensi (rank) dari sebuah numpy array.
* **ndarray.shape**: baris dan kolum dari sebuah numpy array.
* **ndarray.size**: jumlah elemen di dalam numpy array.
* **ndarray.dtype**: tipe data dari elemen yang ada di numpy array.
* **ndarray.itemsize**: ukuran elemen (bytes) yang ada di numpy array.
* **ndarray.data**: buffer untuk menyimpan elemen-elemen di dalam numpy array.

In [ ]:
a = np.array([1, 2, 3])
b = np.array([(1, 2, 3), (4, 5, 6)])

In [ ]:
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)

1
(3,)
3
int64
8


In [ ]:
print(b.ndim)
print(b.shape)
print(b.size)
print(b.dtype)
print(b.itemsize)

2
(2, 3)
6
int64
8


---

# Create Numpy Arrays

* **np.zeros**: isinya semua 0
* **np.ones**: isinya semua 1
* **np.arange**: berikan scope dan panjang dari step
* **np.linspace**: berikan scope dan jumlah elemen yang diinginkan
* **np.random.random**: memberikan angka acak

In [ ]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.arange(1, 2, 0.2)

array([1. , 1.2, 1.4, 1.6, 1.8])

In [ ]:
np.linspace(1, 3, 10)

array([1.        , 1.22222222, 1.44444444, 1.66666667, 1.88888889,
       2.11111111, 2.33333333, 2.55555556, 2.77777778, 3.        ])

In [ ]:
np.random.random((2, 3))

array([[0.63014662, 0.95003617, 0.30874054],
       [0.58230916, 0.25008352, 0.86187682]])

# Shape and Operation

* reshape: mengubah dimensi/shape dari sebuah numpy array.
* vstack: stack numpy arrays secara vertikal.
* hstack: stack numpy arrays secara horizontal.
* vsplit: split numpy arrays secara vertikal.
* hsplit: split numpy arrays secara horizontal.

In [ ]:
a = np.array([(1, 2, 3), (4, 5, 6)])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a = a.reshape(3, -1)
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
b = np.array([(7, 8), (9, 10)])
b

array([[ 7,  8],
       [ 9, 10]])

In [ ]:
np.vstack((a, b))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [ ]:
c = np.array([(11, 12, 13), (14, 15, 16)])
c

array([[11, 12, 13],
       [14, 15, 16]])

In [ ]:
d = np.hstack((a, c))
d

array([[ 1,  2,  3, 11, 12, 13],
       [ 4,  5,  6, 14, 15, 16]])

In [ ]:
d

array([[ 1,  2,  3, 11, 12, 13],
       [ 4,  5,  6, 14, 15, 16]])

In [ ]:
np.vsplit(d, 2)

[array([[ 1,  2,  3, 11, 12, 13]]), array([[ 4,  5,  6, 14, 15, 16]])]

In [ ]:
np.hsplit(d, 3)

[array([[1, 2],
        [4, 5]]), array([[ 3, 11],
        [ 6, 14]]), array([[12, 13],
        [15, 16]])]

In [ ]:
np.hsplit(d, (1, 3)) # split setelah kolum 1 dan kolum 3

[array([[1],
        [4]]), array([[2, 3],
        [5, 6]]), array([[11, 12, 13],
        [14, 15, 16]])]

# Indexing

In [ ]:
data = np.arange(100, 200)
data

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151,
       152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164,
       165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177,
       178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190,
       191, 192, 193, 194, 195, 196, 197, 198, 199])

In [ ]:
data[0]

100

In [ ]:
fives = np.arange(0, 100, 5)
fives

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [ ]:
data[fives]

array([100, 105, 110, 115, 120, 125, 130, 135, 140, 145, 150, 155, 160,
       165, 170, 175, 180, 185, 190, 195])

In [ ]:
data2D = data.reshape(10, -1)
data2D

array([[100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
       [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
       [140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
       [150, 151, 152, 153, 154, 155, 156, 157, 158, 159],
       [160, 161, 162, 163, 164, 165, 166, 167, 168, 169],
       [170, 171, 172, 173, 174, 175, 176, 177, 178, 179],
       [180, 181, 182, 183, 184, 185, 186, 187, 188, 189],
       [190, 191, 192, 193, 194, 195, 196, 197, 198, 199]])

In [ ]:
data2D[2]

array([120, 121, 122, 123, 124, 125, 126, 127, 128, 129])

In [ ]:
data2D[2, 1]

121

In [ ]:
data2D[-2, -1]

189

In [ ]:
data2D[:, 3]

array([103, 113, 123, 133, 143, 153, 163, 173, 183, 193])

In [ ]:
# baris 1, 2 dan 3
# kolum 3 dan 4
data2D[1:4, 3:5]

array([[113, 114],
       [123, 124],
       [133, 134]])

# Mathematics

In [ ]:
numbers = np.random.random((5, 5))
numbers

array([[0.37881531, 0.72638123, 0.29899458, 0.04976302, 0.18611287],
       [0.22969815, 0.5436504 , 0.94611156, 0.27933983, 0.27580926],
       [0.9318502 , 0.16027881, 0.74908333, 0.42193634, 0.68217883],
       [0.81746333, 0.54278588, 0.10077749, 0.77395673, 0.68181386],
       [0.17211614, 0.08959462, 0.75541492, 0.83043718, 0.59005948]])

In [ ]:
print(np.amin(numbers))
print(np.amax(numbers))
print(np.average(numbers))
print(np.sum(numbers))

0.04976301880646605
0.946111563551858
0.4885769338218959
12.214423345547397


In [ ]:
np.sqrt(numbers)

array([[0.61547974, 0.85228002, 0.54680397, 0.22307626, 0.43140801],
       [0.47926834, 0.73732652, 0.97268266, 0.52852609, 0.52517545],
       [0.96532388, 0.40034836, 0.865496  , 0.64956627, 0.82594118],
       [0.90413679, 0.73674004, 0.31745471, 0.87974811, 0.82572021],
       [0.41486882, 0.2993236 , 0.86914608, 0.91128326, 0.76815329]])

In [ ]:
np.sin(numbers)

array([[0.36982003, 0.66416866, 0.29455955, 0.04974248, 0.1850403 ],
       [0.22768361, 0.51726354, 0.81114752, 0.27572112, 0.2723257 ],
       [0.80272468, 0.15959345, 0.68096776, 0.40952773, 0.63048573],
       [0.72941291, 0.51652347, 0.100607  , 0.69897036, 0.6302024 ],
       [0.1712676 , 0.0894748 , 0.68559078, 0.73822634, 0.55641045]])

In [ ]:
np.cos(numbers)

array([[0.92910341, 0.74758276, 0.95563313, 0.99876208, 0.98273093],
       [0.97373517, 0.85582617, 0.5848416 , 0.96123767, 0.96220513],
       [0.59634981, 0.98718282, 0.7323134 , 0.91229767, 0.77620084],
       [0.68407369, 0.85627303, 0.99492624, 0.71515064, 0.7764309 ],
       [0.98522455, 0.99598909, 0.72798714, 0.67455309, 0.83090758]])

In [ ]:
sample = np.arange(1, 21)
sample

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
sample2 = np.arange(51, 71)
sample2

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70])

In [ ]:
sample + sample2

array([52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84,
       86, 88, 90])

In [ ]:
sample2 - sample

array([50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50,
       50, 50, 50])

In [ ]:
sample * sample2

array([  51,  104,  159,  216,  275,  336,  399,  464,  531,  600,  671,
        744,  819,  896,  975, 1056, 1139, 1224, 1311, 1400])

In [ ]:
sample / sample2

array([0.01960784, 0.03846154, 0.05660377, 0.07407407, 0.09090909,
       0.10714286, 0.12280702, 0.13793103, 0.15254237, 0.16666667,
       0.18032787, 0.19354839, 0.20634921, 0.21875   , 0.23076923,
       0.24242424, 0.25373134, 0.26470588, 0.27536232, 0.28571429])

# Matrix

In [ ]:
matrix = np.random.randint(1, 50, 20)
matrix = matrix.reshape(4, -1)
matrix

array([[17, 47, 21,  3, 47],
       [36, 27, 44, 48, 48],
       [49, 20, 39, 24, 43],
       [27, 48, 27,  7, 18]])

In [ ]:
matrix.transpose()

array([[17, 36, 49, 27],
       [47, 27, 20, 48],
       [21, 44, 39, 27],
       [ 3, 48, 24,  7],
       [47, 48, 43, 18]])

In [ ]:
np.dot(matrix, -1)

array([[-17, -47, -21,  -3, -47],
       [-36, -27, -44, -48, -48],
       [-49, -20, -39, -24, -43],
       [-27, -48, -27,  -7, -18]])