<a href="https://colab.research.google.com/github/Rizki-132/Allmateri/blob/main/Regression_dengan_KNN_K_Nearest_Neighbours.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Sampel Dataset

In [ ]:
import pandas as pd

sensus = {
    'Tinggi' : [158, 170, 183, 191, 155, 163, 180, 158, 170],
    'Berat' : [64, 86, 84, 80, 49, 59, 67, 54, 67],
    'Jk' : [
        'pria', 'pria', 'pria', 'pria', 'wanita', 'wanita', 'wanita', 'wanita', 'wanita'
    ]
}

sensus_df = pd.DataFrame(sensus)

sensus_df

Tinggi  Berat      Jk
0     158     64    pria
1     170     86    pria
2     183     84    pria
3     191     80    pria
4     155     49  wanita
5     163     59  wanita
6     180     67  wanita
7     158     54  wanita
8     170     67  wanita

#Features & Target

In [ ]:
import numpy as np

X_train = np.array(sensus_df[['Tinggi', 'Jk']])
y_train = np.array(sensus_df['Berat'])

print(f'X Train :\n{X_train}\n')
print(f'y Train :\n{y_train}\n')

X Train :
[[158 'pria']
 [170 'pria']
 [183 'pria']
 [191 'pria']
 [155 'wanita']
 [163 'wanita']
 [180 'wanita']
 [158 'wanita']
 [170 'wanita']]

y Train :
[64 86 84 80 49 59 67 54 67]



#Proses Dataset Konversi Label Menjadi Numerik Biner

In [ ]:
#transpose mengembalikan rentang sel vertikal sebagai rentang horizontal, atau sebalikny
X_train_transposed = np.transpose(X_train)

print(f'X Train :\n{X_train}\n')
print(f'X Train Transposed :\n{X_train_transposed}\n')

X Train :
[[158 0]
 [170 0]
 [183 0]
 [191 0]
 [155 1]
 [163 1]
 [180 1]
 [158 1]
 [170 1]]

X Train Transposed :
[[158 170 183 191 155 163 180 158 170]
 [0 0 0 0 1 1 1 1 1]]



In [ ]:
from sklearn.preprocessing import LabelBinarizer

lb = LabelBinarizer()
jk_binarised = lb.fit_transform(X_train_transposed[1])

print(f'jk :\n{X_train_transposed[1]}\n')
print(f'jk_binariseed :\n{jk_binarised}\n')

jk :
['pria' 'pria' 'pria' 'pria' 'wanita' 'wanita' 'wanita' 'wanita' 'wanita']

jk_binariseed :
[[0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]]



In [ ]:
jk_binarised = jk_binarised.flatten()
jk_binarised

array([0, 0, 0, 0, 1, 1, 1, 1, 1])

In [ ]:
X_train_transposed[1] = jk_binarised
X_train = X_train_transposed.transpose()

print(f'X_train_transposed:\n{X_train_transposed}\n')
print(f'X_train : {X_train}')

X_train_transposed:
[[158 170 183 191 155 163 180 158 170]
 [0 0 0 0 1 1 1 1 1]]

X_train : [[158 0]
 [170 0]
 [183 0]
 [191 0]
 [155 1]
 [163 1]
 [180 1]
 [158 1]
 [170 1]]


#Training KNN Regression Model

In [12]:
from sklearn.neighbors import KNeighborsRegressor

k = 3
model = KNeighborsRegressor(n_neighbors=k)
model.fit(X_train, y_train)

KNeighborsRegressor(n_neighbors=3)

#Prediksi Berat Badan

In [13]:
X_new = np.array([[155, 1]])
X_new

array([[155,   1]])

In [15]:
y_pred = model.predict(X_new)
y_pred

array([55.66666667])

#Evaluasi KNN Regression Model

In [17]:
X_test = np.array([[168,0],[180, 0],[160,1], [169,1]])
y_test = np.array([65, 96, 52, 67])

print(f'x_test :\n{X_test}\n')
print(f'y_test : {y_test}')

x_test :
[[168   0]
 [180   0]
 [160   1]
 [169   1]]

y_test : [65 96 52 67]


In [18]:
y_pred = model.predict(X_test)
y_pred

array([70.66666667, 79.        , 59.        , 70.66666667])